### ISSUE TITLE
Error on Windows

### ISSUE THREAD

**Issue by robokang** [omarrayyann/MujocoAR#3]
When running the Fruits Pick and Place, PushT, Study Desk, and Blocks Stacking examples in a Windows environment, the following error message appears.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "...\Anaconda3\envs\py39\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "...\Anaconda3\envs\py39\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "...\Anaconda3\envs\py39\lib\site-packages\mujoco_ar\connector.py", line 197, in _run_event_loop
    self.loop.run_until_complete(self._start())
  File "...\Anaconda3\envs\py39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "...\Anaconda3\envs\py39\lib\site-packages\mujoco_ar\connector.py", line 171, in _start
    self._kill_process_using_port(self.port)
  File "...\Anaconda3\envs\py39\lib\site-packages\mujoco_ar\connector.py", line 117, in _kill_process_using_port
    os.system(f'taskkill /PID {pid} /F')
UnboundLocalError: local variable 'pid' referenced before assignment
```

If there is any way to solve this problem, please let me know.

**Comment by omarrayyann** [comment]
Hello @robokang, thanks for flagging this issue. It was a Windows-only bug, and it should be fixed now. Try updating the library: ```pip install --upgrade mujoco_ar```. Let me know if you encounter any issues.
